In [16]:
#!pip install keras
#Remove '#' in above line if not installed keras
import keras
import numpy as np
from sklearn.datasets import load_iris
dataset=load_iris()
##How data looks like?
print(dataset)


{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [17]:
##Step : 1 : Know the data
print(type(dataset))
print(len(dataset))
#Dataset is in bunch format. Bunch is a dictionary like object
print(dataset.keys())
#we try to find out what values are stored in these attributes
print(dataset['data'][0:5])
print(dataset['target'][0:5])
print(dataset['target_names'][0:5])
print(dataset['DESCR'])
print(dataset['feature_names'])
print(dataset['filename'])
#next we define our x and y; y is the dependent on x
x=dataset['data']
print(len(x)) #To check length of dataset
y=dataset['target']
print(len(y))
print(x[0])
print(y[0])

<class 'sklearn.utils._bunch.Bunch'>
8
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
['setosa' 'versicolor' 'virginica']
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ==============

In [18]:
##Step : 2 : Convert y into one hot encoded vector
#One hot encoding is used because Y has labels (0,1,2)- wich is a categorical data with no ordinal relationship
from keras.utils import to_categorical
Ny=len(np.unique(y))
print(Ny)
Y=to_categorical(y,num_classes=Ny)
print(Y[0:5])

3
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [19]:
##Step : 3 : Now we split the data into two parts - one for training anotherfor testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,Y,test_size=0.10,shuffle=True)
print(x_train[0:6])
print(x_test[0:5])
print(y_train[0:6])
print(y_test[0:5])

[[5.4 3.4 1.7 0.2]
 [6.3 2.5 4.9 1.5]
 [5.1 3.8 1.9 0.4]
 [4.6 3.4 1.4 0.3]
 [6.9 3.1 5.1 2.3]
 [4.4 3.2 1.3 0.2]]
[[7.2 3.6 6.1 2.5]
 [6.2 2.8 4.8 1.8]
 [4.7 3.2 1.3 0.2]
 [5.7 2.8 4.5 1.3]
 [6.4 3.1 5.5 1.8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
##Step : 4 : Then we normalize teh data
from sklearn.preprocessing import StandardScaler
import numpy as np
scaler=StandardScaler()
scaler.fit(x_train)

X_train=scaler.transform(x_train)
X_test=scaler.transform(x_test)
print(np.amax(X_train,axis=0))
print(np.amin(X_train,axis=0))

[2.45856609 3.02305312 1.81237489 1.75209644]
[-1.81796619 -2.44273489 -1.52919132 -1.41398971]


In [21]:
##Step : 5 : Now finally we build the model using keras
!pip install tensorflow
import keras
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(20, input_dim=X_train.shape[1], activation='relu'))

keras.layers.Dropout(0.2)
model.add(Dense(20, activation='relu'))
keras.layers.Dropout(0.2)
model.add(Dense(20, activation='relu'))
keras.layers.Dropout(0.2)
model.add(Dense(3, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [22]:
##Step : 6 : Know the model
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 20)                100       
                                                                 
 dense_5 (Dense)             (None, 20)                420       
                                                                 
 dense_6 (Dense)             (None, 20)                420       
                                                                 
 dense_7 (Dense)             (None, 3)                 63        
                                                                 
Total params: 1,003
Trainable params: 1,003
Non-trainable params: 0
_________________________________________________________________


In [23]:
##Step : 7 : Train the model

model.fit(X_train, y_train, epochs=198, batch_size=88, validation_split=0.1)

Epoch 1/198
2/2 [==============================] - 4s 448ms/step - loss: 1.1387 - accuracy: 0.0331 - val_loss: 1.0885 - val_accuracy: 0.0000e+00
Epoch 2/198
2/2 [==============================] - 0s 66ms/step - loss: 1.1127 - accuracy: 0.0661 - val_loss: 1.0578 - val_accuracy: 0.0714
Epoch 3/198
2/2 [==============================] - 0s 74ms/step - loss: 1.0888 - accuracy: 0.1157 - val_loss: 1.0277 - val_accuracy: 0.2143
Epoch 4/198
2/2 [==============================] - 0s 62ms/step - loss: 1.0666 - accuracy: 0.2066 - val_loss: 0.9992 - val_accuracy: 0.7143
Epoch 5/198
2/2 [==============================] - 0s 59ms/step - loss: 1.0444 - accuracy: 0.5041 - val_loss: 0.9716 - val_accuracy: 0.7143
Epoch 6/198
2/2 [==============================] - 0s 66ms/step - loss: 1.0246 - accuracy: 0.5620 - val_loss: 0.9450 - val_accuracy: 0.7857
Epoch 7/198
2/2 [==============================] - 0s 75ms/step - loss: 1.0038 - accuracy: 0.5785 - val_loss: 0.9199 - val_accuracy: 0.7857
Epoch 8/198
2/2

In [24]:
##Step : 8 : Get the accuracy of model on testing data
testing=model.evaluate(x_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1]+'uracy of model on the testing data', testing[1]*100))

1/1 [==============================] - 0s 33ms/step - loss: 6.2522 - accuracy: 0.5333

accuracyuracy of model on the testing data: 53.33%


In [25]:
##Step : 9 : Evaluate our model
from sklearn.metrics import classification_report, confusion_matrix
predictions = np.argmax(model.predict(x_test), axis=1)
Y_test = np.argmax(y_test,axis=1)
print(confusion_matrix(Y_test,predictions))
print(classification_report(Y_test,predictions))

1/1 [==============================] - 0s 75ms/step
[[0 3 0]
 [0 0 4]
 [0 0 8]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.00      0.00      0.00         4
           2       0.67      1.00      0.80         8

    accuracy                           0.53        15
   macro avg       0.22      0.33      0.27        15
weighted avg       0.36      0.53      0.43        15



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
